language: node_js
node_js:
  - "node"
  - "iojs"
  - "7"
  - "6"
  - "4"
  - "lts/*"
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
cache:
    directories:
        - test_suite
        - node_modules

